### ISSUE TITLE
Tests are always passing in latest 0.10+nuget package

### ISSUE THREAD

**Issue by msmolka** [TNG/ArchUnitNET#162]
I have test:

```c#
using static ArchUnitNET.Fluent.ArchRuleDefinition;
```

```c#
    [Fact]
    public void EntityFrameworkCore_ShouldOnlyResideInInfrastructure_WhenEntityFrameworkCoreIsUsed()
    {
        IArchRule validatorNamingConventionRule = Classes().That()
            .DependOnAny("Microsoft.EntityFrameworkCore").And().DoNotResideInNamespace("Microsoft.Extensions.DependencyInjection")
            .Should()
            .NotResideInNamespace("Infrastructure.Data.EntityFramework");

        validatorNamingConventionRule.Check(Architecture);
    }
```
That is properly failing in version 0.9.1 but passing in version 0.10+

**Comment by fgather** [comment]
Hi @msmolka , how do you load your assemblies?

In cases where many third-party dependencies are loaded, it is not a good idea to fully load all of them, since it might take a while. As long as the recursive parameter in the LoadAssemblyIncludingDependencies is not set, it would only load direct dependencies and create stubs for all the others. -> does the test work if you set this recurse parameter?

Best Regards,
Florian

**Comment by msmolka** [comment]
Whole my code is above. How can I modify it to load assembles? 

```c#
Classes(true)
```
also not working.

**Comment by brandhuf** [comment]
With version 0.10 the default behaviour for string matching was changed. Previously
```cs
DependOnAny("Microsoft.EntityFrameworkCore")
```
found all types which had a dependency to a type with `Microsoft.EntityFrameworkCore` contained in it's full name. Now it only find dependencies to types with the exact full name `Microsoft.EntityFrameworkCore`. The same is true for all other methods which use strings as matching parameters. You can specify to use regex instead if you want to match parts of the full name:
```cs
DependOnAny("Microsoft.EntityFrameworkCore", useRegularExpressions:true)
```
Maybe this is the reason the behaviour of your rule changed?

**Comment by msmolka** [comment]
Looks working now
