### ISSUE TITLE
How to find and verify nested types for a given type?

### ISSUE THREAD

**Issue by Yaevh** [TNG/ArchUnitNET#179]
In my current project I have the following requirement:

There are certain classes (representing commands) that should be validated. The validator for each command should be contained in a nested class within that command and implement `FluentValidation.IValidator`.
The example command class should thus look like this:
```csharp
public class MyCommand : ICommand
{
    // some properties
    
    public class Validator : AbstractValidator<MyCommand>
    {
        // definitions of validation rules
    }
}
```

So the way to go should probably be like this:
1. load up the assembly into `ArchLoader`
2. filter all the relevant classes (in this case, classes that implement `ICommand` interface)
3. for each filtered class get its nested classes
4. check that for each filtered class at least one nested class satisfies some predicate

Checking whether a given type is nested is pretty simple, but I can't find a way to easily obtain any information about the relationship between nesting and nested types (both from nested and nesting type's perspective), and thus I'm stuck on step 3.

I've thrown together a query that extracts all the commands and their potential validators by joining them on `IType.FullName` (using [MoreLINQ](https://github.com/morelinq/MoreLINQ)'s `LeftJoin`, example below), but that's much less intuitive and requires much more work than simply querying a type for its nested types. Is there a way to get this kind of information without resorting to such hacks?

```csharp
[Fact]
public void All_commands_must_have_validators()
{
    static string ExtractValidatedClass(Class validatorClass)
    {
        if (validatorClass.IsNested)
            return validatorClass.FullName.Substring(0, validatorClass.FullName.LastIndexOf("+"));
        else
            return null;
    }


    var architecture = new ArchLoader().LoadAssemblies(
            typeof(MyProject.MarkerInterface).Assembly,
            typeof(FluentValidation.IValidator).Assembly)
        .Build();
        
    var commandType = architecture.GetInterfaceOfType(typeof(ICommmand));
    var validatorType = architecture.GetInterfaceOfType(typeof(FluentValidation.IValidator));

    var commands = architecture.Classes.Where(x => x.IsAssignableTo(commandType));
    var validators = architecture.Classes.Where(x => x.IsAssignableTo(validatorType));

    var commandsAndValidators = commands.LeftJoin(validators,
        command => command.FullName,
        validator => ExtractValidatedClassName(validator),
        command => new { command, validator = (Class?)null },
        (command, validator) => new { command, validator })
        .ToList();

    commandsAndValidators.Should().AllSatisfy(x => x.validator.Should().NotBeNull());
}
```

**Comment by fgather** [comment]
@Yaevh , does the change work for you? Feel free to reopen, if you expected something different.

**Comment by Yaevh** [comment]
@fgather Hard to say, as new version hasn't been released yet :)

**Comment by CesarD** [comment]
I have a problem with the way this has been fixed and I'd like to know if somebody can explain it to me:
I have the same scenario: a class that has some nested classes for command, validator and handler. And I want to ensure that these 3 are always nested together.
My problem is that the solution implemented in the lib seems to differ in the concept of what NESTED is: BeNestedIn seems to check that the class is actually nested inside another, but IsNestedIn seems to check whether the class is assignable to another... Am I interpreting everything right? If so, why is it this way? IMHO this doesn't make sense since one thing is not really related to each other. Having a class nested within another is not the same as one being assignable to another, or am I missing something? Because when I am filtering which classes I want to work with, I'll ve selecting them with one criteria, but then when I want to check them in some custom predicate and using IsNestedIn, it will be performing that check with a whole different criteria.

Has somebody experienced the same??


cc: @Yaevh @fgather @andredered
