### ISSUE TITLE
Is ExampleArchUnitTestCooking test working for .Net Core SDK(3.1.101)

### ISSUE THREAD

**Issue by vikaskerni** [TNG/ArchUnitNET#19]
I am very excited about this great. framework . Great work
I have a question .
Is ExampleArchUnitTestCooking  working for .Net Core SDK(3.1.101).

I removed the ICook interface from FrenchChef and ran the test.
Test is still passing. I was expecting it to fail
Looking forward to your answer.

**Comment by fgather** [comment]
Hi,

You're completely right, this assertion does not work. The "ImplementsInterface"-method returns a boolean and the XUnit Assert.All method expects an exception if something does not match, so that does not fit well. Personally I recommend the Fluent API for tests. 

I'll fix this example test right away. Thanks for finding this issue!

**Comment by fgather** [comment]
Done and I also found another occasion of this interpretation of the XUnit Assert.All method. Thanks again!

**Comment by vikaskerni** [comment]
Thank you very much. I am very excited about this framework.
Great work.
