### ISSUE TITLE
Missing Classes in Architecture 

### ISSUE THREAD

**Issue by SamuelMuellerKMS** [TNG/ArchUnitNET#292]
We have considered, that classes from different assemblies with the same name and namespace only shown once. 
We've the following assembly situation: 

- Assembly.UI (with root namespace "Assembly")
  - FeatureA/Class1
- Assembly.Business (with root namespace "Assembly")
  -  FeatureA/Class1

If you now setup an architecture for both assemblies and check that Classes must not end with '1' only one Class is found.
For reproduction i've added a little sample
[ArchUnitSample.zip](https://github.com/user-attachments/files/16838417/ArchUnitSample.zip)

**Comment by fgather** [comment]
Hi @SamuelMuellerKMS,

that is a very interesting set-up. I'd expect that this might not only confuse ArchUnit, but also the developers? Since we identify classes by their namespace/name/generics constellation this is not a real surprise. Let's see if we can easily improve on that.

**Comment by alexanderlinne** [comment]
C# does provide `… .GetType().AssemblyQualifiedName` which would return e.g. `Assembly.FeatureA.Class1, Assembly.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`. The first step here would be to change the Loader to use the AssemblyQualifiedName instead of just the FullName. I will have another look into this later today.

After that we could also expose the AssemblyQualifiedName in the interface. This would involve new methods for the fluent API and changes to the error messages. But this will definitely take some more time.

**Comment by fgather** [comment]
@SamuelMuellerKMS we just merged a fix for this into main. Would you be able to test it and give feedback?
