### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by sibber5** [TNG/ArchUnitNET#329]
I couldn't find this documented anywhere, so i fell back to the java docs on this.
They suggest using `ArchCondition.Or(ArchCondition)` and they give the example:
```
classes()...should(
   bePublic().or(
     bePrivate().and(haveNameMatching(pattern))
   )
 )
 ```
 
 but i cant pass `BePriavate()` to `Or()` like in the java lib, it seems to expect me to to
 ```
Classes().Should()
    .BePublic()
    .Or(Classes().Should().BePrivate().AndShould().HaveName(pattern))
```

but this doesnt seem correct at all, so how should operator precedence be dealt with?

**Comment by mak638** [comment]
Hi @sibber5, your Example
```
Classes().Should()
   .BePublic()
   .Or(Classes().Should().BePrivate().AndShould().HaveName(pattern))
```
does not work because it checks both rules separately. I.e. the above rule is fulfilled if either all classes in your architecture are public or if all classes in your architecture are private and have the corresponding name.

To fix your problem one would need to use `OrShould()` instead of `Or()`. Please note though, that the operator precedence for these logical conjunctions is not following the usual logical precedence that `And` is stronger than `Or` but instead just goes from left to right. I.e. there is a difference between
```
Classes().Should()
  .BePublic()
  .OrShould()
  .BePrivate()
  .AndShould()
  .HaveName(pattern) // -> all classes are either public or private, and all of them are following the naming pattern
```
and
```
Classes().Should()
  .BePrivate()
  .AndShould()
  .HaveName(pattern)
  .OrShould()
  .BePublic() // -> classes either are private and follow the naming pattern, or they are public (and not necessarily follow any naming pattern)
```

As this problem can not be fixed easily (Fluent Assertion in general does not support `Or()` because of this, see for example https://stackoverflow.com/questions/34654341/fluent-assertion-for-or-condition) we would instead recommend splitting your test as follows to achieve the same result:
```
Classes()
  .Should()
  .BePublic()
  .OrShould()
  .BePrivate()
  .Check(Architecture)

Classes()
  .That()
  .ArePrivate()
  .Should()
  .HaveName(pattern)
  .Check(Architecture)
```
