### ISSUE TITLE
Static function call though lambda is not recongized as dependency

### ISSUE THREAD

**Issue by hoffmannjanos** [TNG/ArchUnitNET#71]
The framework doesn't find the dependency to SomeOtherClass (which is in another project) in such code:
```
Func<DateTime, DateTime> dateFunc = d => d.AddDays(1);
if (someCondition)
{
    dateFunc = SomeOtherClass.SomeStaticFunction;
} 
return dateFunc(someDate);
```

**Comment by fgather** [comment]
We found the issue. The example provided is not enough for the reproduction though. The issue happens in an interesting edge case, when using yield and calling a static method from this generator function. In this case the C# compiler creates some compiler generated classes, which would not be an issue on its own, since ArchUnit traverses the whole tree of compiler generated methods. But in order to handle the method access properly, the compiler uses MethodReferences instead of FieldReferences, which is something ArchUnit does not expect. We are working on a fix.

**Comment by brandhuf** [comment]
Can you test it again with the newest release?

**Comment by hoffmannjanos** [comment]
It seems to be working fine now. Thank you.

**Comment by fgather** [comment]
great, thanks for the quick feedback!
